[workspace]
members = [
    "acpi",
    "kernel",
    "kernel_loader",
    "kernel_shared",
    "multiboot",
    "std"
]
resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
strip = true
