[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
kernel_shared = { path = "../kernel_shared" }
std = { path = "../std" }
acpi = { path = "../acpi" }
multiboot = { path = "../multiboot" }

[lib]
crate-type = ["staticlib"]
