[package]
name = "kernel_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
paste = "1.0.15"
log = "0.4.27"
bitflags = "2.9.1"
std = { path = "../std" }
multiboot = { path = "../multiboot" }

[features]
ZERO_OUT_FREED_MEMORY = []